Repository QASTUDIODEV/SERVER_QASTUDIO, pull requests merged in 2025-02, with the labels that each got.

#164 ✨ Feature: 페이지네이션 있는 프로젝트 별 역할 list 조회 api 구현
  src/main/java/qastudio/backend/domain/project/controller/CharacterController.java
  src/main/java/qastudio/backend/domain/project/converter/CharacterConverter.java
  src/main/java/qastudio/backend/domain/project/dto/response/CharacterResponse.java
  src/main/java/qastudio/backend/domain/project/repository/CharacterTableRepository/CharacterTableRepositoryCustom.java
  src/main/java/qastudio/backend/domain/project/repository/CharacterTableRepository/CharacterTableRepositoryImpl.java
  src/main/java/qastudio/backend/domain/project/service/CharacterQueryService.java
  src/main/java/qastudio/backend/domain/project/service/CharacterQueryServiceImpl.java
Labels: ✨ Feature

#166 Feature : 세션 연결 종료
  src/main/java/qastudio/backend/domain/selenium/service/SeleniumExecutionServiceImpl.java
  src/main/java/qastudio/backend/domain/selenium/util/SeleniumActionExecutor.java
  src/main/java/qastudio/backend/global/websocket/handler/SeleniumWebSocketHandler.java
Labels: ✨ Feature

#168 🐞 Fix: 역할/시나리오 삭제 시 NullPointerException 예외처리
  src/main/java/qastudio/backend/domain/project/service/CharacterCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/scenario/service/ScenarioCommandServiceImpl.java
  src/main/java/qastudio/backend/global/apiPayload/code/status/ErrorStatus.java
Labels: 🐞 BugFix

#170 ✨ Feature: 역할 list 조회 시, 시나리오 list도 함께 조회되게 추가
  src/main/java/qastudio/backend/domain/project/converter/CharacterConverter.java
  src/main/java/qastudio/backend/domain/project/dto/response/CharacterResponse.java
  src/main/java/qastudio/backend/domain/project/service/CharacterQueryServiceImpl.java
  src/main/java/qastudio/backend/domain/scenario/repository/ScenarioRepositoryCustom.java
  src/main/java/qastudio/backend/domain/scenario/repository/ScenarioRepositoryImpl.java
Labels: ✨ Feature

#172 🐞 Fix: 역할/시나리오 삭제 시 NullPointerException 예외처리 수정
  src/main/java/qastudio/backend/domain/project/service/CharacterCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/scenario/service/ScenarioCommandServiceImpl.java
Labels: 🐞 BugFix

#176 :sparkles: Feature: cors 경로 추가
  src/main/java/qastudio/backend/global/security/SecurityConfig.java
Labels: ✨ Feature

#179 ✨ Feature: 역할 생성/수정 시 ai request에 path_list 추가
  src/main/java/qastudio/backend/domain/project/service/CharacterCommandServiceImpl.java
Labels: ✨ Feature

#178 🔨 Refactor: fetch join을 이용하여 N+1 문제 해결
  src/main/java/qastudio/backend/domain/project/converter/PageConverter.java
  src/main/java/qastudio/backend/domain/project/entity/Page.java
  src/main/java/qastudio/backend/domain/project/repository/Page/PageRepository.java
  src/main/java/qastudio/backend/domain/project/repository/Page/PageRepositoryCustom.java
  src/main/java/qastudio/backend/domain/project/repository/Page/PageRepositoryImpl.java
  src/main/java/qastudio/backend/domain/project/service/PageQueryServiceImpl.java
Labels: :hammer: Refactor

#199 Refactor: selenium setting
  .github/workflows/test_deploy.yml
  src/main/java/qastudio/backend/domain/selenium/service/SeleniumExecutionServiceImpl.java
Labels: :hammer: Refactor

#207 ✨ Feature - JWT 토큰으로 프로젝트 초대 요청, 수락 구현
  src/main/java/qastudio/backend/domain/auth/service/EmailQueryService.java
  src/main/java/qastudio/backend/domain/auth/service/EmailQueryServiceImpl.java
  src/main/java/qastudio/backend/domain/project/controller/TeamMemberController.java
  src/main/java/qastudio/backend/domain/project/converter/TeamMemberConverter.java
  src/main/java/qastudio/backend/domain/project/dto/response/TeamMemberResponse.java
  src/main/java/qastudio/backend/domain/project/service/TeamMemberCommandService.java
  src/main/java/qastudio/backend/domain/project/service/TeamMemberCommandServiceImpl.java
  src/main/java/qastudio/backend/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/qastudio/backend/global/security/jwt/InviteTokenProvider.java
  src/main/resources/templates/invite.html
Labels: ✨ Feature

#214 ✨ Feature: 프로젝트 생성 시 필수 필드값 수정
  src/main/java/qastudio/backend/domain/project/dto/request/ProjectRequest.java
Labels: ✨ Feature

#218 ⚙️ Setting: 도커 ram 제한 추가
  .github/workflows/test_deploy.yml
Labels: ⚙ Setting

#231 Fix : 프론트와 연결
  src/main/java/qastudio/backend/domain/selenium/service/SeleniumExecutionServiceImpl.java
  src/main/java/qastudio/backend/domain/selenium/util/SeleniumActionExecutor.java
Labels: 🐞 BugFix

#232 ✨ Feature: Redis를 통해 프로젝트별 초대된 유저 관리, 검증 API 개발
  src/main/java/qastudio/backend/domain/project/controller/TeamMemberController.java
  src/main/java/qastudio/backend/domain/project/converter/TeamMemberConverter.java
  src/main/java/qastudio/backend/domain/project/dto/request/TeamMemberRequest.java
  src/main/java/qastudio/backend/domain/project/dto/response/TeamMemberResponse.java
  src/main/java/qastudio/backend/domain/project/service/TeamMemberCommandService.java
  src/main/java/qastudio/backend/domain/project/service/TeamMemberCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/project/service/TeamMemberQueryService.java
  src/main/java/qastudio/backend/domain/project/service/TeamMemberQueryServiceImpl.java
  src/main/java/qastudio/backend/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ Feature, :hammer: Refactor

#233 Fix : 가비지 컬렉션 실행
  src/main/java/qastudio/backend/domain/selenium/service/SeleniumExecutionServiceImpl.java
  src/main/java/qastudio/backend/domain/selenium/util/SeleniumActionExecutor.java
Labels: 🐞 BugFix

#234 Fix : " -> """ 로 감싸는 형식 수정
  src/main/java/qastudio/backend/domain/selenium/controller/SeleniumExecutionController.java
  src/main/java/qastudio/backend/domain/selenium/dto/SeleniumExecutionResponse.java
  src/main/java/qastudio/backend/domain/selenium/dto/response/PageResultResponse.java
  src/main/java/qastudio/backend/domain/selenium/dto/response/SeleniumExecutionResponse.java
  src/main/java/qastudio/backend/domain/selenium/service/SeleniumExecutionService.java
  src/main/java/qastudio/backend/domain/selenium/service/SeleniumExecutionServiceImpl.java
  src/main/java/qastudio/backend/domain/selenium/util/SeleniumActionExecutor.java
  src/main/java/qastudio/backend/global/util/MemoryUtils.java
  src/main/java/qastudio/backend/global/websocket/handler/SeleniumWebSocketHandler.java
Labels: 🐞 BugFix, ✨ Feature

#235 fix : 웹소켓 응답 형식 수정
  build.gradle
  src/main/java/qastudio/backend/domain/selenium/util/SeleniumActionExecutor.java
  src/main/java/qastudio/backend/global/websocket/handler/SeleniumWebSocketHandler.java
Labels: 🐞 BugFix

#229 🔨 Refactor: 마이페이지 N+1 문제 해결
  src/main/java/qastudio/backend/domain/user/converter/UserConverter.java
  src/main/java/qastudio/backend/domain/user/repository/User/UserRepositoryImpl.java
Labels: :hammer: Refactor

#239 :hammer: Refactor: cicd 시간 늘리기
  .github/workflows/test_deploy.yml
Labels: :hammer: Refactor

#226 🔨 Refactor: 테스트 통계 N+1 문제 해결
  src/main/java/qastudio/backend/domain/project/entity/Project.java
  src/main/java/qastudio/backend/domain/test/controller/TestController.java
  src/main/java/qastudio/backend/domain/test/converter/TestConverter.java
  src/main/java/qastudio/backend/domain/test/repository/TestRepositoryCustom.java
  src/main/java/qastudio/backend/domain/test/repository/TestRepositoryImpl.java
  src/main/java/qastudio/backend/domain/test/service/TestQueryService.java
  src/main/java/qastudio/backend/domain/test/service/TestQueryServiceImpl.java
Labels: :hammer: Refactor

#249 🐞 Fix: 프로젝트 리스트 조회 NullPointerException 예외처리
  src/main/java/qastudio/backend/domain/user/converter/UserConverter.java
Labels: 🐞 BugFix

#250 feature : 웹소켓 응답에 phase 추가
  src/main/java/qastudio/backend/domain/selenium/dto/response/PageResultResponse.java
  src/main/java/qastudio/backend/domain/selenium/service/SeleniumExecutionServiceImpl.java
  src/main/java/qastudio/backend/domain/selenium/util/SeleniumActionExecutor.java
  src/main/java/qastudio/backend/global/websocket/handler/SeleniumWebSocketHandler.java
Labels: ✨ Feature

#253 🔨 Refactor: 소셜, 팀원 초대 이메일 redirect url 프론트 배포 서버로 변경
  src/main/java/qastudio/backend/domain/auth/controller/AuthController.java
  src/main/java/qastudio/backend/domain/project/service/TeamMemberQueryServiceImpl.java
  src/main/java/qastudio/backend/global/security/oauth/handler/OAuth2FailureHandler.java
  src/main/java/qastudio/backend/global/security/oauth/handler/OAuth2SuccessHandler.java
Labels: :hammer: Refactor

#254 fix : url request body로 받기
  src/main/java/qastudio/backend/domain/selenium/controller/SeleniumExecutionController.java
  src/main/java/qastudio/backend/domain/selenium/dto/request/FetchPageSourceRequest.java
  src/main/java/qastudio/backend/global/websocket/handler/SeleniumWebSocketHandler.java
Labels: 🐞 BugFix

#258 ✨ Feature: 테스트 리스트 조회 response에 projectUrl 추가
  src/main/java/qastudio/backend/domain/test/converter/TestConverter.java
  src/main/java/qastudio/backend/domain/test/dto/response/TestResponse.java
Labels: ✨ Feature

#270 ✨ Feature: 프로젝트 수정 API 작성
  src/main/java/qastudio/backend/domain/project/controller/ProjectController.java
  src/main/java/qastudio/backend/domain/project/converter/UserProjectConverter.java
  src/main/java/qastudio/backend/domain/project/dto/request/ProjectRequest.java
  src/main/java/qastudio/backend/domain/project/entity/Project.java
  src/main/java/qastudio/backend/domain/project/repository/UserProject/UserProjectRepository.java
  src/main/java/qastudio/backend/domain/project/service/ProjectCommandService.java
  src/main/java/qastudio/backend/domain/project/service/ProjectCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/project/service/TeamMemberQueryService.java
  src/main/java/qastudio/backend/domain/project/service/TeamMemberQueryServiceImpl.java
Labels: ✨ Feature

#273 Feature : 시나리오 수정 api
  src/main/java/qastudio/backend/domain/scenario/controller/ScenarioController.java
  src/main/java/qastudio/backend/domain/scenario/dto/request/ScenarioRequest.java
  src/main/java/qastudio/backend/domain/scenario/entity/Scenario.java
  src/main/java/qastudio/backend/domain/scenario/service/ActionCommandService.java
  src/main/java/qastudio/backend/domain/scenario/service/ActionCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/scenario/service/ScenarioCommandService.java
  src/main/java/qastudio/backend/domain/scenario/service/ScenarioCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/selenium/service/SeleniumExecutionServiceImpl.java
  src/main/java/qastudio/backend/domain/selenium/util/SeleniumActionExecutor.java
  src/main/java/qastudio/backend/domain/selenium/util/SeleniumHtmlCssUtil.java
Labels: ✨ Feature

#275 feature : 시나리오 수정 시 캐릭터 아이디 수정 추가
  src/main/java/qastudio/backend/domain/scenario/dto/request/ScenarioRequest.java
  src/main/java/qastudio/backend/domain/scenario/entity/Scenario.java
  src/main/java/qastudio/backend/domain/scenario/service/ScenarioCommandServiceImpl.java
Labels: ✨ Feature

#276 fix : class 네임 셀레니움에서는 미변경
  src/main/java/qastudio/backend/domain/selenium/util/SeleniumActionExecutor.java
Labels: 🐞 BugFix

#278 fix : js 일부 반환
  src/main/java/qastudio/backend/domain/selenium/util/SeleniumActionExecutor.java
Labels: 🐞 BugFix

#281 fix : 데이터 동기화
  src/main/java/qastudio/backend/domain/selenium/service/SeleniumExecutionServiceImpl.java
Labels: 🐞 BugFix

#282 feature : wait 추가
  src/main/java/qastudio/backend/domain/selenium/service/SeleniumExecutionServiceImpl.java
  src/main/java/qastudio/backend/domain/selenium/util/SeleniumActionExecutor.java
Labels: ✨ Feature

#285 Feature/#228 front conn
  src/main/java/qastudio/backend/domain/selenium/service/SeleniumExecutionServiceImpl.java
Labels: 🐞 BugFix

#288 fix : 대기 시간 수정 및 selenium hub
  .github/workflows/test_deploy.yml
  src/main/java/qastudio/backend/domain/selenium/service/SeleniumExecutionServiceImpl.java
  src/main/java/qastudio/backend/domain/selenium/util/ActionExecutor.java
  src/main/java/qastudio/backend/domain/selenium/util/CustomActionExecutor.java
  src/main/java/qastudio/backend/domain/selenium/util/SeleniumActionExecutor.java
Labels: 🐞 BugFix

#292 🐛 Fix: 테스트 리스트의 Name을 시나리오 이름으로 수정
  src/main/java/qastudio/backend/domain/scenario/service/ScenarioQueryServiceImpl.java
  src/main/java/qastudio/backend/domain/selenium/dto/request/SeleniumExecutionRequest.java
  src/main/java/qastudio/backend/domain/selenium/service/SeleniumExecutionServiceImpl.java
Labels: 🐞 BugFix

#293 fix : 대기 방식 수정
  src/main/java/qastudio/backend/domain/selenium/service/SeleniumExecutionServiceImpl.java
  src/main/java/qastudio/backend/domain/selenium/util/ActionExecutor.java
  src/main/java/qastudio/backend/domain/selenium/util/CustomActionExecutor.java
  src/main/java/qastudio/backend/domain/selenium/util/SeleniumActionExecutor.java
Labels: 🐞 BugFix

#294 Feature : sleep 수정
  src/main/java/qastudio/backend/domain/selenium/dto/request/SeleniumExecutionRequest.java
  src/main/java/qastudio/backend/domain/selenium/util/ActionExecutor.java
  src/main/java/qastudio/backend/domain/selenium/util/CustomActionExecutor.java
  src/main/java/qastudio/backend/domain/selenium/util/SeleniumActionExecutor.java
Labels: 🐞 BugFix

#295 ✨ Feature: 역할 수정 시, ai Scenario 생성 선택 기능 추가
  src/main/java/qastudio/backend/domain/project/controller/CharacterController.java
  src/main/java/qastudio/backend/domain/project/dto/request/CharacterRequest.java
  src/main/java/qastudio/backend/domain/project/service/CharacterCommandService.java
  src/main/java/qastudio/backend/domain/project/service/CharacterCommandServiceImpl.java
Labels: ✨ Feature

#296 fix : 대기 시간 줄이기
  src/main/java/qastudio/backend/domain/selenium/util/ActionExecutor.java
  src/main/java/qastudio/backend/domain/selenium/util/CustomActionExecutor.java
  src/main/java/qastudio/backend/domain/selenium/util/SeleniumActionExecutor.java
Labels: 🐞 BugFix

#297 feature : 실행 시에도 / 검증
  src/main/java/qastudio/backend/domain/selenium/service/SeleniumExecutionServiceImpl.java
Labels: ✨ Feature

#300 🐛 Fix: cascade 설정 추가
  src/main/java/qastudio/backend/domain/project/entity/Page.java
  src/main/java/qastudio/backend/domain/test/entity/Test.java
Labels: 🐞 BugFix
