Repository QASTUDIODEV/SERVER_QASTUDIO, pull requests merged in 2025-01, with the labels that each got.

#3 ✨ Feature: 엔티티 생성
  README.md
  src/main/java/qastudio/backend/domain/project/entity/CharacterTable.java
  src/main/java/qastudio/backend/domain/project/entity/Page.java
  src/main/java/qastudio/backend/domain/project/entity/Project.java
  src/main/java/qastudio/backend/domain/project/entity/ProjectStack.java
  src/main/java/qastudio/backend/domain/project/entity/UserProject.java
  src/main/java/qastudio/backend/domain/project/entity/enums/Role.java
  src/main/java/qastudio/backend/domain/project/entity/enums/ViewType.java
  src/main/java/qastudio/backend/domain/scenario/entity/ActionTable.java
  src/main/java/qastudio/backend/domain/scenario/entity/Feature.java
  src/main/java/qastudio/backend/domain/scenario/entity/Scenario.java
  src/main/java/qastudio/backend/domain/test/entity/Error.java
  src/main/java/qastudio/backend/domain/test/entity/Test.java
  src/main/java/qastudio/backend/domain/test/entity/enums/State.java
  src/main/java/qastudio/backend/domain/user/entity/AccountTable.java
  src/main/java/qastudio/backend/domain/user/entity/User.java
  src/main/java/qastudio/backend/domain/user/entity/enums/EmailType.java
Labels: ✨ Feat

#4 ✨ Feature: 자체 로그인/회원가입 구현
  .gitignore
  build.gradle
  src/main/java/qastudio/backend/domain/auth/controller/AuthController.java
  src/main/java/qastudio/backend/domain/auth/converter/AuthConverter.java
  src/main/java/qastudio/backend/domain/auth/dto/request/AuthRequest.java
  src/main/java/qastudio/backend/domain/auth/service/AuthService.java
  src/main/java/qastudio/backend/domain/auth/service/AuthServiceImpl.java
  src/main/java/qastudio/backend/domain/auth/service/CustomUserDetailsService.java
  src/main/java/qastudio/backend/domain/user/entity/AccountTable.java
  src/main/java/qastudio/backend/domain/user/entity/User.java
  src/main/java/qastudio/backend/domain/user/repository/AccountTableRepository.java
  src/main/java/qastudio/backend/domain/user/repository/UserRepository.java
  src/main/java/qastudio/backend/global/apiPayload/code/exception/ExceptionAdvice.java
  src/main/java/qastudio/backend/global/apiPayload/code/exception/GeneralException.java
  src/main/java/qastudio/backend/global/apiPayload/code/exception/custom/AuthException.java
  src/main/java/qastudio/backend/global/apiPayload/code/exception/custom/BadRequestException.java
  src/main/java/qastudio/backend/global/apiPayload/code/exception/custom/TokenException.java
  src/main/java/qastudio/backend/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/qastudio/backend/global/config/SecurityConfig.java
  src/main/java/qastudio/backend/global/handler/annotation/Auth.java
  src/main/java/qastudio/backend/global/handler/resolver/AuthResolver.java
  src/main/java/qastudio/backend/jwt/JwtTokenFilter.java
  src/main/java/qastudio/backend/jwt/JwtTokenProvider.java
  src/main/java/qastudio/backend/jwt/TokenInfo.java
Labels: ✨ Feat

#9 🔨 Refactor: 역할, 페이지 엔터티 다대다 관계로 변경
  src/main/java/qastudio/backend/domain/project/entity/Page.java
  src/main/java/qastudio/backend/domain/project/entity/PageRole.java
Labels: :hammer: Refactor

#12 🌏 Deploy: cicd 구축
  .github/workflows/test_deploy.yml
  Dockerfile
  build.gradle
  src/main/java/qastudio/backend/global/comon/HealthController.java
Labels: 🚀 Deploy

#14 🐛 Fix: cicd yml 수정
  .github/workflows/test_deploy.yml
Labels: 🐞 BugFix

#19 🐛 Fix: yml 수정 & health checking url 시큐리티 수정
  .github/workflows/test_deploy.yml
  Dockerfile
  src/main/java/qastudio/backend/global/config/SecurityConfig.java
  src/main/java/qastudio/backend/jwt/JwtTokenFilter.java
Labels: 🐞 BugFix

#21 📝 Docs: 프로젝트, 페이지, 역할 API 문서화
  src/main/java/qastudio/backend/domain/project/controller/CharacterController.java
  src/main/java/qastudio/backend/domain/project/controller/PageController.java
  src/main/java/qastudio/backend/domain/project/controller/ProjectController.java
  src/main/java/qastudio/backend/domain/project/controller/TeamMemberController.java
  src/main/java/qastudio/backend/domain/project/converter/CharacterConverter.java
  src/main/java/qastudio/backend/domain/project/converter/TeamMemberConverter.java
  src/main/java/qastudio/backend/domain/project/dto/request/PageRequest.java
  src/main/java/qastudio/backend/domain/project/dto/request/ProjectRequest.java
  src/main/java/qastudio/backend/domain/project/dto/request/TeamMemberRequest.java
  src/main/java/qastudio/backend/domain/project/dto/response/CharacterResponse.java
  src/main/java/qastudio/backend/domain/project/dto/response/PageResponse.java
  src/main/java/qastudio/backend/domain/project/dto/response/ProjectResponse.java
  src/main/java/qastudio/backend/domain/project/dto/response/TeamMemberResponse.java
  src/main/java/qastudio/backend/domain/project/service/CharacterQueryService.java
  src/main/java/qastudio/backend/domain/project/service/CharacterQueryServiceImpl.java
  src/main/java/qastudio/backend/domain/project/service/PageQueryService.java
  src/main/java/qastudio/backend/domain/project/service/PageQueryServiceImpl.java
  src/main/java/qastudio/backend/domain/project/service/ProjectQueryService.java
  src/main/java/qastudio/backend/domain/project/service/ProjectQueryServiceImpl.java
  src/main/java/qastudio/backend/domain/project/service/TeamMemberQueryService.java
  src/main/java/qastudio/backend/domain/project/service/TeamMemberQueryServiceImpl.java
  src/main/java/qastudio/backend/global/apiPayload/code/status/ErrorStatus.java
Labels: 📝 Docs, ✨ Feat, :hammer: Refactor

#23 🐛 Fix: docker container 이름 고유화
  .github/workflows/test_deploy.yml
Labels: 🐞 BugFix

#25 :sparkles: Feature: discord 500에러 연동
  src/main/java/qastudio/backend/global/apiPayload/code/exception/ExceptionAdvice.java
  src/main/java/qastudio/backend/global/apiPayload/code/exception/discord/DiscordClient.java
  src/main/java/qastudio/backend/global/apiPayload/code/exception/discord/DiscordMessage.java
Labels: ✨ Feat

#27 🐛 Fix: Auth token 생성 시 userId 형변환 문제 해결
  src/main/java/qastudio/backend/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/qastudio/backend/global/config/WebConfig.java
  src/main/java/qastudio/backend/global/handler/resolver/AuthResolver.java
  src/main/java/qastudio/backend/jwt/JwtTokenFilter.java
  src/main/java/qastudio/backend/jwt/JwtTokenProvider.java
Labels: 🐞 BugFix

#31 📝 Docs: 프로젝트 생성 Swagger 명세서 작성
  src/main/java/qastudio/backend/domain/project/controller/ProjectController.java
  src/main/java/qastudio/backend/domain/project/dto/request/ProjectRequest.java
  src/main/java/qastudio/backend/domain/project/service/ProjectQueryService.java
  src/main/java/qastudio/backend/domain/project/service/ProjectQueryServiceImpl.java
Labels: 📝 Docs

#34 📝 Docs: 프로젝트 역할 관련 Swagger 명세서 작성
  src/main/java/qastudio/backend/domain/project/controller/CharacterController.java
  src/main/java/qastudio/backend/domain/project/dto/request/CharacterRequest.java
  src/main/java/qastudio/backend/domain/project/dto/response/CharacterResponse.java
  src/main/java/qastudio/backend/domain/project/service/CharacterQueryService.java
  src/main/java/qastudio/backend/domain/project/service/CharacterQueryServiceImpl.java
Labels: 📝 Docs

#37 📝 Docs: 테스트 관련 Swagger 명세서 작성
  src/main/java/qastudio/backend/domain/test/controller/ErrorController.java
  src/main/java/qastudio/backend/domain/test/controller/TestController.java
  src/main/java/qastudio/backend/domain/test/dto/response/ErrorResponse.java
  src/main/java/qastudio/backend/domain/test/dto/response/TestResponse.java
  src/main/java/qastudio/backend/domain/test/service/ErrorQueryService.java
  src/main/java/qastudio/backend/domain/test/service/ErrorQueryServiceImpl.java
  src/main/java/qastudio/backend/domain/test/service/TestQueryService.java
  src/main/java/qastudio/backend/domain/test/service/TestQueryServiceImpl.java
  src/main/java/qastudio/backend/global/apiPayload/code/status/ErrorStatus.java
Labels: 📝 Docs, ✨ Feat

#41 🔨 Refactor: Restful api규칙 적용
  src/main/java/qastudio/backend/domain/project/controller/CharacterController.java
  src/main/java/qastudio/backend/domain/project/controller/PageController.java
  src/main/java/qastudio/backend/domain/project/controller/ProjectController.java
  src/main/java/qastudio/backend/domain/project/controller/TeamMemberController.java
Labels: :hammer: Refactor

#39 ✨ Feature: 이메일 인증번호 전송 구현
  build.gradle
  src/main/java/qastudio/backend/domain/auth/controller/AuthController.java
  src/main/java/qastudio/backend/domain/auth/dto/request/EmailRequest.java
  src/main/java/qastudio/backend/domain/auth/dto/response/EmailResponse.java
  src/main/java/qastudio/backend/domain/auth/service/EmailService.java
  src/main/java/qastudio/backend/domain/auth/service/EmailServiceImpl.java
  src/main/java/qastudio/backend/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/qastudio/backend/global/config/SecurityConfig.java
  src/main/java/qastudio/backend/jwt/JwtTokenFilter.java
  src/main/resources/templates/mail.html
Labels: ✨ Feat

#35 Docs : 시나리오 생성 및 조회 API 명세서 작성
  src/main/java/qastudio/backend/domain/scenario/controller/ActionController.java
  src/main/java/qastudio/backend/domain/scenario/controller/ScenarioController.java
  src/main/java/qastudio/backend/domain/scenario/controller/ScenarioExecutionController.java
  src/main/java/qastudio/backend/domain/scenario/converter/.keep
  src/main/java/qastudio/backend/domain/scenario/dto/request/ActionUpdateRequest.java
  src/main/java/qastudio/backend/domain/scenario/dto/request/EnvironmentRequest.java
  src/main/java/qastudio/backend/domain/scenario/dto/request/ScenarioRequest.java
  src/main/java/qastudio/backend/domain/scenario/dto/response/ActionResponse.java
  src/main/java/qastudio/backend/domain/scenario/dto/response/ExecutionResultResponse.java
  src/main/java/qastudio/backend/domain/scenario/dto/response/ScenarioDetailResponse.java
  src/main/java/qastudio/backend/domain/scenario/dto/response/ScenarioResponse.java
  src/main/java/qastudio/backend/domain/scenario/repository/ActionTableRepository.java
  src/main/java/qastudio/backend/domain/scenario/repository/CharacterTableRepository.java
  src/main/java/qastudio/backend/domain/scenario/repository/ScenarioRepository.java
  src/main/java/qastudio/backend/domain/scenario/service/ActionCommandService.java
  src/main/java/qastudio/backend/domain/scenario/service/ActionCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/scenario/service/ScenarioCommandService.java
  src/main/java/qastudio/backend/domain/scenario/service/ScenarioCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/scenario/service/ScenarioExecutionService.java
  src/main/java/qastudio/backend/domain/scenario/service/ScenarioExecutionServiceImpl.java
  src/main/java/qastudio/backend/domain/scenario/service/ScenarioQueryService.java
  src/main/java/qastudio/backend/domain/scenario/service/ScenarioQueryServiceImpl.java
Labels: 📝 Docs

#42 📝 Docs: 소셜 로그인 Swagger 명세서 작성
  src/main/java/qastudio/backend/domain/auth/controller/AuthController.java
Labels: 📝 Docs

#47 ✨ Feature: Cors 설정
  src/main/java/qastudio/backend/global/config/WebConfig.java
Labels: ✨ Feat

#48 🔨 Refactor: TeamMembers API 설계 변경
  src/main/java/qastudio/backend/domain/project/controller/TeamMemberController.java
Labels: :hammer: Refactor

#44 📝 Docs: 마이페이지 Swagger 명세서 작성
  src/main/java/qastudio/backend/domain/user/controller/UserController.java
  src/main/java/qastudio/backend/domain/user/dto/request/UserRequest.java
  src/main/java/qastudio/backend/domain/user/dto/response/UserResponse.java
  src/main/java/qastudio/backend/domain/user/service/UserQueryService.java
  src/main/java/qastudio/backend/domain/user/service/UserQueryServiceImpl.java
Labels: 📝 Docs

#49 🐞 Fix: TeamMemberRequest github dto 반영
  src/main/java/qastudio/backend/domain/project/dto/request/TeamMemberRequest.java
Labels: 🐞 BugFix

#54 ✨ Feature: websocket setting
  build.gradle
  src/main/java/qastudio/backend/global/apiPayload/code/exception/custom/ChatException.java
  src/main/java/qastudio/backend/global/websocket/WebSocketConfig.java
  src/main/java/qastudio/backend/global/websocket/handler/CustomWebSocketExceptionHandler.java
  src/main/java/qastudio/backend/global/websocket/handler/TextHandler.java
Labels: ✨ Feat

#59 🐛 Fix: cors 에러 해결
  src/main/java/qastudio/backend/global/config/SecurityConfig.java
  src/main/java/qastudio/backend/global/config/WebConfig.java
Labels: 🐞 BugFix

#62 ✨ Feature: swagger url 추가
  src/main/java/qastudio/backend/global/config/SecurityConfig.java
Labels: ✨ Feat

#71 ✨ Feature: 프로젝트 역할 관련 api 구현
  src/main/java/qastudio/backend/domain/project/controller/CharacterController.java
  src/main/java/qastudio/backend/domain/project/converter/CharacterConverter.java
  src/main/java/qastudio/backend/domain/project/dto/request/CharacterRequest.java
  src/main/java/qastudio/backend/domain/project/dto/response/CharacterResponse.java
  src/main/java/qastudio/backend/domain/project/entity/CharacterTable.java
  src/main/java/qastudio/backend/domain/project/entity/Project.java
  src/main/java/qastudio/backend/domain/project/repository/CharacterTableRepository/CharacterTableRepositoryCustom.java
  src/main/java/qastudio/backend/domain/project/repository/CharacterTableRepository/CharacterTableRepositoryImpl.java
  src/main/java/qastudio/backend/domain/project/repository/Page/PageRepositoryCustom.java
  src/main/java/qastudio/backend/domain/project/repository/Page/PageRepositoryImpl.java
  src/main/java/qastudio/backend/domain/project/repository/PageRole/PageRoleRepositoryCustom.java
  src/main/java/qastudio/backend/domain/project/repository/PageRole/PageRoleRepositoryImpl.java
  src/main/java/qastudio/backend/domain/project/service/CharacterCommandService.java
  src/main/java/qastudio/backend/domain/project/service/CharacterCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/project/service/CharacterQueryService.java
  src/main/java/qastudio/backend/domain/project/service/CharacterQueryServiceImpl.java
  src/main/java/qastudio/backend/domain/scenario/controller/ScenarioController.java
  src/main/java/qastudio/backend/domain/scenario/dto/request/ScenarioRequest.java
  src/main/java/qastudio/backend/domain/scenario/repository/ScenarioRepository.java
  src/main/java/qastudio/backend/domain/scenario/repository/ScenarioRepositoryCustom.java
  src/main/java/qastudio/backend/domain/scenario/repository/ScenarioRepositoryImpl.java
  src/main/java/qastudio/backend/domain/scenario/service/ScenarioCommandService.java
  src/main/java/qastudio/backend/domain/scenario/service/ScenarioCommandServiceImpl.java
Labels: ✨ Feat

#73 🔨 Refactor: Page API 설계 수정
  src/main/java/qastudio/backend/domain/project/controller/PageController.java
Labels: :hammer: Refactor

#64 🔨 Refactor: 이메일 인증번호 html 추가 및 service 분리
  src/main/java/qastudio/backend/domain/auth/controller/AuthController.java
  src/main/java/qastudio/backend/domain/auth/converter/EmailConverter.java
  src/main/java/qastudio/backend/domain/auth/service/AuthServiceImpl.java
  src/main/java/qastudio/backend/domain/auth/service/CustomUserDetailsService.java
  src/main/java/qastudio/backend/domain/auth/service/EmailCommandService.java
  src/main/java/qastudio/backend/domain/auth/service/EmailCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/auth/service/EmailQueryService.java
  src/main/java/qastudio/backend/domain/auth/service/EmailQueryServiceImpl.java
  src/main/resources/templates/mail.html
Labels: :hammer: Refactor

#76 ✨ Feature: 회원가입 시 사용자 프로필 설정
  src/main/java/qastudio/backend/domain/auth/controller/AuthController.java
  src/main/java/qastudio/backend/domain/auth/service/AuthCommandService.java
  src/main/java/qastudio/backend/domain/auth/service/AuthCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/auth/service/AuthQueryService.java
  src/main/java/qastudio/backend/domain/auth/service/AuthQueryServiceImpl.java
  src/main/java/qastudio/backend/domain/auth/service/AuthService.java
  src/main/java/qastudio/backend/domain/user/controller/UserController.java
  src/main/java/qastudio/backend/domain/user/dto/request/UserRequest.java
  src/main/java/qastudio/backend/domain/user/entity/User.java
  src/main/java/qastudio/backend/domain/user/service/UserCommandService.java
  src/main/java/qastudio/backend/domain/user/service/UserCommandServiceImpl.java
Labels: ✨ Feat

#69 Feature : 시나리오 생성, 조회 API
  src/main/java/qastudio/backend/domain/scenario/controller/ScenarioController.java
  src/main/java/qastudio/backend/domain/scenario/converter/.keep
  src/main/java/qastudio/backend/domain/scenario/converter/ActionConverter.java
  src/main/java/qastudio/backend/domain/scenario/converter/ScenarioConverter.java
  src/main/java/qastudio/backend/domain/scenario/dto/Element.java
  src/main/java/qastudio/backend/domain/scenario/dto/request/ScenarioRequest.java
  src/main/java/qastudio/backend/domain/scenario/dto/response/ScenarioDetailResponse.java
  src/main/java/qastudio/backend/domain/scenario/entity/ActionTable.java
  src/main/java/qastudio/backend/domain/scenario/repository/ActionTableRepository.java
  src/main/java/qastudio/backend/domain/scenario/service/ActionCommandService.java
  src/main/java/qastudio/backend/domain/scenario/service/ActionCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/scenario/service/ScenarioCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/scenario/service/ScenarioQueryServiceImpl.java
  src/main/java/qastudio/backend/global/config/SecurityConfig.java
  src/main/java/qastudio/backend/global/util/JsonUtil.java
Labels: ✨ Feat

#80 🐞 Fix: annotation 중복 에러 해결
  src/main/java/qastudio/backend/domain/scenario/service/ScenarioCommandServiceImpl.java
Labels: 🐞 BugFix

#77 ✨ Feature: 마이페이지 관련 API 구현
  src/main/java/qastudio/backend/domain/project/entity/Project.java
  src/main/java/qastudio/backend/domain/user/controller/UserController.java
  src/main/java/qastudio/backend/domain/user/converter/UserConverter.java
  src/main/java/qastudio/backend/domain/user/dto/response/UserResponse.java
  src/main/java/qastudio/backend/domain/user/entity/AccountTable.java
  src/main/java/qastudio/backend/domain/user/entity/User.java
  src/main/java/qastudio/backend/domain/user/repository/User/UserRepositoryCustom.java
  src/main/java/qastudio/backend/domain/user/repository/User/UserRepositoryImpl.java
  src/main/java/qastudio/backend/domain/user/service/UserCommandService.java
  src/main/java/qastudio/backend/domain/user/service/UserCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/user/service/UserQueryService.java
  src/main/java/qastudio/backend/domain/user/service/UserQueryServiceImpl.java
Labels: ✨ Feat

#82 ✨ Feature: 비밀번호 변경 API 구현
  src/main/java/qastudio/backend/domain/auth/controller/AuthController.java
  src/main/java/qastudio/backend/domain/auth/converter/AuthConverter.java
  src/main/java/qastudio/backend/domain/auth/dto/request/AuthRequest.java
  src/main/java/qastudio/backend/domain/auth/service/AuthCommandService.java
  src/main/java/qastudio/backend/domain/auth/service/AuthCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/auth/service/AuthQueryService.java
  src/main/java/qastudio/backend/domain/auth/service/AuthQueryServiceImpl.java
  src/main/java/qastudio/backend/domain/auth/service/EmailCommandService.java
  src/main/java/qastudio/backend/domain/auth/service/EmailCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/auth/service/EmailQueryService.java
  src/main/java/qastudio/backend/domain/auth/service/EmailQueryServiceImpl.java
  src/main/java/qastudio/backend/domain/user/entity/AccountTable.java
  src/main/java/qastudio/backend/domain/user/repository/AccountTable/AccountTableRepositoryCustom.java
  src/main/java/qastudio/backend/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/qastudio/backend/global/config/SecurityConfig.java
  src/main/java/qastudio/backend/jwt/JwtTokenFilter.java
Labels: ✨ Feat

#84 ✨ Feature: 프로젝트 생성 api 구현
  src/main/java/qastudio/backend/domain/project/controller/ProjectController.java
  src/main/java/qastudio/backend/domain/project/converter/ProjectConverter.java
  src/main/java/qastudio/backend/domain/project/dto/request/ProjectRequest.java
  src/main/java/qastudio/backend/domain/project/dto/response/ProjectResponse.java
  src/main/java/qastudio/backend/domain/project/service/ProjectCommandService.java
  src/main/java/qastudio/backend/domain/project/service/ProjectCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/project/service/ProjectQueryService.java
  src/main/java/qastudio/backend/domain/project/service/ProjectQueryServiceImpl.java
Labels: ✨ Feature

#86 ✨ Feature: 소셜 로그인 API 구현
  src/main/java/qastudio/backend/domain/auth/controller/AuthController.java
  src/main/java/qastudio/backend/domain/auth/converter/AuthConverter.java
  src/main/java/qastudio/backend/domain/auth/dto/response/AuthResponse.java
  src/main/java/qastudio/backend/domain/auth/service/AuthCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/auth/service/AuthQueryServiceImpl.java
  src/main/java/qastudio/backend/domain/project/service/TeamMemberCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/user/repository/User/UserRepository.java
  src/main/java/qastudio/backend/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/qastudio/backend/global/config/SecurityConfig.java
  src/main/java/qastudio/backend/global/oauth/CustomOAuth2UserService.java
  src/main/java/qastudio/backend/global/oauth/OAuth2SuccessHandler.java
  src/main/java/qastudio/backend/global/oauth/OAuth2UserInfo.java
  src/main/java/qastudio/backend/jwt/JwtTokenFilter.java
  src/main/java/qastudio/backend/jwt/JwtTokenProvider.java
Labels: ✨ Feature

#85 ✨ Feature: 프로젝트 정보 등록 AI 연결
  build.gradle
  src/main/java/qastudio/backend/domain/project/controller/ProjectController.java
  src/main/java/qastudio/backend/domain/project/converter/ProjectConverter.java
  src/main/java/qastudio/backend/domain/project/dto/response/ProjectResponse.java
  src/main/java/qastudio/backend/domain/project/entity/Project.java
  src/main/java/qastudio/backend/domain/project/entity/enums/ProjectStack.java
  src/main/java/qastudio/backend/domain/project/service/ProjectCommandService.java
  src/main/java/qastudio/backend/domain/project/service/ProjectCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/project/service/ProjectQueryService.java
  src/main/java/qastudio/backend/domain/project/service/ProjectQueryServiceImpl.java
Labels: ✨ Feature

#90 🔨 Refactor: userId로 프로젝트 생성되게 수정
  src/main/java/qastudio/backend/domain/project/controller/ProjectController.java
  src/main/java/qastudio/backend/domain/project/converter/ProjectConverter.java
  src/main/java/qastudio/backend/domain/project/dto/request/ProjectRequest.java
  src/main/java/qastudio/backend/domain/project/dto/response/ProjectResponse.java
  src/main/java/qastudio/backend/domain/project/entity/UserProject.java
  src/main/java/qastudio/backend/domain/project/service/ProjectCommandService.java
  src/main/java/qastudio/backend/domain/project/service/ProjectCommandServiceImpl.java
Labels: :hammer: Refactor

#93 🔨 Refactor: 회원가입, 로그인, 최초 프로필 설정 response 수정
  src/main/java/qastudio/backend/domain/auth/controller/AuthController.java
  src/main/java/qastudio/backend/domain/auth/converter/AuthConverter.java
  src/main/java/qastudio/backend/domain/auth/dto/response/AuthResponse.java
  src/main/java/qastudio/backend/domain/auth/service/AuthCommandService.java
  src/main/java/qastudio/backend/domain/auth/service/AuthCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/auth/service/AuthQueryService.java
  src/main/java/qastudio/backend/domain/auth/service/AuthQueryServiceImpl.java
  src/main/java/qastudio/backend/domain/user/controller/UserController.java
  src/main/java/qastudio/backend/domain/user/converter/UserConverter.java
  src/main/java/qastudio/backend/domain/user/dto/response/UserResponse.java
  src/main/java/qastudio/backend/domain/user/service/UserCommandService.java
  src/main/java/qastudio/backend/domain/user/service/UserCommandServiceImpl.java
  src/main/java/qastudio/backend/global/config/PasswordConfig.java
  src/main/java/qastudio/backend/global/config/SecurityConfig.java
  src/main/java/qastudio/backend/global/oauth/OAuth2SuccessHandler.java
Labels: :hammer: Refactor

#94 ✨ Feature: Character 생성할 때 필요한 프로젝트 path를 모두 조회하는 API 개발
  src/main/java/qastudio/backend/domain/project/controller/CharacterController.java
  src/main/java/qastudio/backend/domain/project/converter/CharacterConverter.java
  src/main/java/qastudio/backend/domain/project/dto/response/CharacterResponse.java
  src/main/java/qastudio/backend/domain/project/service/CharacterCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/project/service/CharacterQueryService.java
  src/main/java/qastudio/backend/domain/project/service/CharacterQueryServiceImpl.java
Labels: ✨ Feature

#100 ✨ Feature: 오류 조회 API 구현
  src/main/java/qastudio/backend/domain/test/controller/ErrorController.java
  src/main/java/qastudio/backend/domain/test/converter/ErrorConverter.java
  src/main/java/qastudio/backend/domain/test/dto/response/ErrorResponse.java
  src/main/java/qastudio/backend/domain/test/entity/Error.java
  src/main/java/qastudio/backend/domain/test/repository/ErrorRepository.java
  src/main/java/qastudio/backend/domain/test/repository/ErrorRepositoryCustom.java
  src/main/java/qastudio/backend/domain/test/repository/ErrorRepositoryImpl.java
  src/main/java/qastudio/backend/domain/test/service/ErrorQueryService.java
  src/main/java/qastudio/backend/domain/test/service/ErrorQueryServiceImpl.java
  src/main/java/qastudio/backend/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ Feature

#96 ✨ Feature: 프로젝트 생성하면서 팀원 초대
  src/main/java/qastudio/backend/domain/project/controller/TeamMemberController.java
  src/main/java/qastudio/backend/domain/project/converter/ProjectConverter.java
  src/main/java/qastudio/backend/domain/project/converter/TeamMemberConverter.java
  src/main/java/qastudio/backend/domain/project/dto/request/ProjectRequest.java
  src/main/java/qastudio/backend/domain/project/entity/Project.java
  src/main/java/qastudio/backend/domain/project/service/ProjectCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/project/service/TeamMemberCommandService.java
  src/main/java/qastudio/backend/domain/project/service/TeamMemberCommandServiceImpl.java
Labels: ✨ Feature

#99 🔨 Refactor: 소셜 로그인 전달 로직 수정
  build.gradle
  src/main/java/qastudio/backend/domain/auth/controller/AuthController.java
  src/main/java/qastudio/backend/domain/auth/converter/AuthConverter.java
  src/main/java/qastudio/backend/domain/auth/service/AuthQueryService.java
  src/main/java/qastudio/backend/domain/auth/service/AuthQueryServiceImpl.java
  src/main/java/qastudio/backend/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/qastudio/backend/global/config/SecurityConfig.java
  src/main/java/qastudio/backend/global/oauth/OAuth2SuccessHandler.java
  src/main/java/qastudio/backend/jwt/JwtTokenProvider.java
Labels: :hammer: Refactor

#101 🔨 Refactor: 소셜 로그인 프론트 성공 url 변경
  src/main/java/qastudio/backend/global/oauth/OAuth2SuccessHandler.java
Labels: :hammer: Refactor

#103 🔨 Refactor: 소셜 로그인 개발용 cookie 허용
  src/main/java/qastudio/backend/global/oauth/OAuth2SuccessHandler.java
Labels: :hammer: Refactor

#104 🔨 Refactor: 통합 계정 회원가입/로그인으로 수정
  src/main/java/qastudio/backend/domain/auth/converter/AuthConverter.java
  src/main/java/qastudio/backend/domain/auth/service/AuthCommandService.java
  src/main/java/qastudio/backend/domain/auth/service/AuthCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/auth/service/AuthQueryService.java
  src/main/java/qastudio/backend/domain/auth/service/AuthQueryServiceImpl.java
  src/main/java/qastudio/backend/domain/user/repository/AccountTable/AccountTableRepository.java
  src/main/java/qastudio/backend/global/oauth/CustomOAuth2UserService.java
  src/main/java/qastudio/backend/global/oauth/OAuth2SuccessHandler.java
Labels: :hammer: Refactor

#102 ✨ Feature: 테스트 통계 조회 API 구현
  src/main/java/qastudio/backend/domain/test/controller/TestController.java
  src/main/java/qastudio/backend/domain/test/converter/TestConverter.java
  src/main/java/qastudio/backend/domain/test/dto/response/TestResponse.java
  src/main/java/qastudio/backend/domain/test/repository/TestRepository.java
  src/main/java/qastudio/backend/domain/test/repository/TestRepositoryCustom.java
  src/main/java/qastudio/backend/domain/test/repository/TestRepositoryImpl.java
  src/main/java/qastudio/backend/domain/test/service/TestQueryService.java
  src/main/java/qastudio/backend/domain/test/service/TestQueryServiceImpl.java
Labels: ✨ Feature

#107 ✨ Feature: 엔티티 수정
  src/main/java/qastudio/backend/domain/scenario/controller/ScenarioController.java
  src/main/java/qastudio/backend/domain/scenario/converter/ActionConverter.java
  src/main/java/qastudio/backend/domain/scenario/entity/ActionTable.java
  src/main/java/qastudio/backend/domain/scenario/entity/Scenario.java
  src/main/java/qastudio/backend/domain/scenario/service/ScenarioQueryService.java
  src/main/java/qastudio/backend/domain/scenario/service/ScenarioQueryServiceImpl.java
  src/main/java/qastudio/backend/domain/test/entity/Test.java
Labels: ✨ Feature

#109 BUGFIX : 시나리오 명칭 변경
  src/main/java/qastudio/backend/domain/scenario/converter/ActionConverter.java
  src/main/java/qastudio/backend/domain/scenario/service/ScenarioQueryService.java
  src/main/java/qastudio/backend/domain/scenario/service/ScenarioQueryServiceImpl.java
Labels: 🐞 BugFix

#105 Feature : 셀레니움 실행 기능 추가
  build.gradle
  src/main/java/qastudio/backend/domain/scenario/controller/ScenarioController.java
  src/main/java/qastudio/backend/domain/scenario/controller/ScenarioExecutionController.java
  src/main/java/qastudio/backend/domain/scenario/converter/ActionConverter.java
  src/main/java/qastudio/backend/domain/scenario/dto/request/EnvironmentRequest.java
  src/main/java/qastudio/backend/domain/scenario/dto/request/ScenarioExecutionRequest.java
  src/main/java/qastudio/backend/domain/scenario/dto/request/ScenarioRequest.java
  src/main/java/qastudio/backend/domain/scenario/dto/response/ExecutionResultResponse.java
  src/main/java/qastudio/backend/domain/scenario/entity/ActionTable.java
  src/main/java/qastudio/backend/domain/scenario/service/ActionCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/scenario/service/ScenarioExecutionService.java
  src/main/java/qastudio/backend/domain/scenario/service/ScenarioExecutionServiceImpl.java
  src/main/java/qastudio/backend/domain/scenario/service/SeleniumService.java
  src/main/java/qastudio/backend/domain/selenium/controller/SeleniumExecutionController.java
  src/main/java/qastudio/backend/domain/selenium/dto/request/SeleniumExecutionRequest.java
  src/main/java/qastudio/backend/domain/selenium/dto/response/SeleniumExecutionResponse.java
  src/main/java/qastudio/backend/domain/selenium/entity/enums/ActionType.java
  src/main/java/qastudio/backend/domain/selenium/entity/enums/LocatorType.java
  src/main/java/qastudio/backend/domain/selenium/service/SeleniumExecutionService.java
  src/main/java/qastudio/backend/domain/selenium/service/SeleniumExecutionServiceImpl.java
  src/main/java/qastudio/backend/domain/selenium/util/ActionExecutor.java
  src/main/java/qastudio/backend/domain/selenium/util/LocatorActionValidator.java
  src/main/java/qastudio/backend/domain/selenium/util/LocatorUtils.java
  src/main/java/qastudio/backend/domain/selenium/util/SeleniumActionExecutor.java
  src/main/java/qastudio/backend/global/util/HtmlCssFormatter.java
  src/main/java/qastudio/backend/global/websocket/WebSocketConfig.java
  src/main/java/qastudio/backend/global/websocket/handler/SeleniumWebSocketHandler.java
Labels: ✨ Feature

#110 🐞 Fix: 자체 로그인 서비스 에러 해결
  src/main/java/qastudio/backend/domain/auth/service/AuthCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/user/repository/AccountTable/AccountTableRepository.java
Labels: 🐞 BugFix

#112 🔨 Refactor: 소셜 로그인 전달 query param으로 재수정
  src/main/java/qastudio/backend/domain/auth/controller/AuthController.java
  src/main/java/qastudio/backend/domain/auth/converter/AuthConverter.java
  src/main/java/qastudio/backend/global/config/SecurityConfig.java
  src/main/java/qastudio/backend/global/oauth/OAuth2SuccessHandler.java
Labels: :hammer: Refactor

#113 Feature : 시나리오 실행, 추가
  src/main/java/qastudio/backend/domain/scenario/controller/ScenarioController.java
  src/main/java/qastudio/backend/domain/scenario/controller/ScenarioExecutionController.java
  src/main/java/qastudio/backend/domain/scenario/converter/ActionConverter.java
  src/main/java/qastudio/backend/domain/scenario/converter/ScenarioActionConverter.java
  src/main/java/qastudio/backend/domain/scenario/converter/ScenarioConverter.java
  src/main/java/qastudio/backend/domain/scenario/dto/Element.java
  src/main/java/qastudio/backend/domain/scenario/dto/FeatureData.java
  src/main/java/qastudio/backend/domain/scenario/dto/request/ActionRequest.java
  src/main/java/qastudio/backend/domain/scenario/dto/request/ActionUpdateRequest.java
  src/main/java/qastudio/backend/domain/scenario/dto/request/BaseUrlRequest.java
  src/main/java/qastudio/backend/domain/scenario/dto/request/ScenarioRequest.java
  src/main/java/qastudio/backend/domain/scenario/dto/response/ActionResponse.java
  src/main/java/qastudio/backend/domain/scenario/dto/response/FeatureJson.java
  src/main/java/qastudio/backend/domain/scenario/dto/response/ScenarioDetailResponse.java
  src/main/java/qastudio/backend/domain/scenario/dto/response/ScenarioResponse.java
  src/main/java/qastudio/backend/domain/scenario/entity/Feature.java
  src/main/java/qastudio/backend/domain/scenario/repository/FeatureRepository.java
  src/main/java/qastudio/backend/domain/scenario/repository/FeatureRepositoryCustom.java
  src/main/java/qastudio/backend/domain/scenario/repository/FeatureRepositoryImpl.java
  src/main/java/qastudio/backend/domain/scenario/repository/ScenarioRepository.java
  src/main/java/qastudio/backend/domain/scenario/service/ActionCommandService.java
  src/main/java/qastudio/backend/domain/scenario/service/ActionCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/scenario/service/ScenarioCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/scenario/service/ScenarioQueryService.java
  src/main/java/qastudio/backend/domain/scenario/service/ScenarioQueryServiceImpl.java
  src/main/java/qastudio/backend/domain/selenium/dto/request/SeleniumExecutionRequest.java
  src/main/java/qastudio/backend/domain/selenium/service/SeleniumExecutionServiceImpl.java
  src/main/java/qastudio/backend/domain/selenium/util/ActionExecutor.java
  src/main/java/qastudio/backend/domain/selenium/util/SeleniumActionExecutor.java
  src/main/java/qastudio/backend/domain/test/dto/request/TestRequest.java
  src/main/java/qastudio/backend/domain/test/repository/TestRepositoryCustom.java
  src/main/java/qastudio/backend/domain/test/repository/TestRepositoryImpl.java
  src/main/java/qastudio/backend/domain/test/service/TestCommandService.java
  src/main/java/qastudio/backend/domain/test/service/TestCommandServiceImpl.java
  src/main/java/qastudio/backend/global/util/SecurityUtils.java
Labels: ✨ Feature

#115 ✨ Feature: 테스트 관련 API 구현
  src/main/java/qastudio/backend/domain/test/controller/TestController.java
  src/main/java/qastudio/backend/domain/test/converter/ErrorConverter.java
  src/main/java/qastudio/backend/domain/test/converter/TestConverter.java
  src/main/java/qastudio/backend/domain/test/dto/response/ErrorResponse.java
  src/main/java/qastudio/backend/domain/test/dto/response/TestResponse.java
  src/main/java/qastudio/backend/domain/test/entity/Test.java
  src/main/java/qastudio/backend/domain/test/repository/TestRepositoryCustom.java
  src/main/java/qastudio/backend/domain/test/repository/TestRepositoryImpl.java
  src/main/java/qastudio/backend/domain/test/service/TestCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/test/service/TestQueryService.java
  src/main/java/qastudio/backend/domain/test/service/TestQueryServiceImpl.java
Labels: ✨ Feature

#117 🔨 Refactor: 로그인 쿠키 전달 및 프로필 조회 API
  src/main/java/qastudio/backend/domain/auth/controller/AuthController.java
  src/main/java/qastudio/backend/domain/auth/converter/AuthConverter.java
  src/main/java/qastudio/backend/domain/auth/service/AuthCommandService.java
  src/main/java/qastudio/backend/domain/auth/service/AuthCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/user/controller/UserController.java
  src/main/java/qastudio/backend/domain/user/repository/AccountTable/AccountTableRepository.java
  src/main/java/qastudio/backend/domain/user/repository/User/UserRepository.java
  src/main/java/qastudio/backend/domain/user/service/UserQueryService.java
  src/main/java/qastudio/backend/domain/user/service/UserQueryServiceImpl.java
  src/main/java/qastudio/backend/global/config/SecurityConfig.java
  src/main/java/qastudio/backend/global/oauth/CustomOAuth2UserService.java
  src/main/java/qastudio/backend/global/oauth/OAuth2SuccessHandler.java
  src/main/java/qastudio/backend/jwt/JwtTokenFilter.java
Labels: :hammer: Refactor

#119 🔨 Refactor: 로그인/회원가입 쿠키 전달 방법 수정
  src/main/java/qastudio/backend/domain/auth/converter/AuthConverter.java
  src/main/java/qastudio/backend/domain/auth/service/AuthCommandServiceImpl.java
  src/main/java/qastudio/backend/global/oauth/OAuth2SuccessHandler.java
Labels: :hammer: Refactor

#120 🔨 Refactor: 자체 회원가입/로그인 쿠키 전달 수정
  src/main/java/qastudio/backend/domain/auth/controller/AuthController.java
  src/main/java/qastudio/backend/domain/auth/converter/AuthConverter.java
  src/main/java/qastudio/backend/domain/auth/dto/response/AuthResponse.java
  src/main/java/qastudio/backend/domain/auth/service/AuthCommandService.java
  src/main/java/qastudio/backend/domain/auth/service/AuthCommandServiceImpl.java
  src/main/java/qastudio/backend/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/qastudio/backend/global/security/SecurityConfig.java
  src/main/java/qastudio/backend/global/security/jwt/JwtTokenFilter.java
  src/main/java/qastudio/backend/global/security/jwt/JwtTokenProvider.java
  src/main/java/qastudio/backend/global/security/jwt/TokenInfo.java
  src/main/java/qastudio/backend/global/security/oauth/CustomOAuth2UserService.java
  src/main/java/qastudio/backend/global/security/oauth/OAuth2SuccessHandler.java
  src/main/java/qastudio/backend/global/security/oauth/OAuth2UserInfo.java
Labels: :hammer: Refactor

#121 🔨 Refactor: Cookie secure 설정
  src/main/java/qastudio/backend/domain/auth/converter/AuthConverter.java
Labels: :hammer: Refactor

#122 🔨 Refactor: 프론트 URL https로 수정
  src/main/java/qastudio/backend/domain/auth/service/AuthCommandServiceImpl.java
  src/main/java/qastudio/backend/global/security/SecurityConfig.java
  src/main/java/qastudio/backend/global/security/oauth/OAuth2SuccessHandler.java
Labels: :hammer: Refactor

#123 🔨 Refactor: CORS 경로 구체화
  src/main/java/qastudio/backend/domain/auth/controller/AuthController.java
  src/main/java/qastudio/backend/domain/auth/service/AuthCommandServiceImpl.java
  src/main/java/qastudio/backend/global/security/SecurityConfig.java
  src/main/java/qastudio/backend/global/security/oauth/OAuth2SuccessHandler.java
Labels: :hammer: Refactor

#124 🔨 Refactor: OPTIONS 허용 및 일반 회원가입/로그인 response만 수정(개발용)
  src/main/java/qastudio/backend/domain/auth/controller/AuthController.java
  src/main/java/qastudio/backend/domain/auth/converter/AuthConverter.java
  src/main/java/qastudio/backend/domain/auth/dto/response/AuthResponse.java
  src/main/java/qastudio/backend/domain/auth/service/AuthCommandService.java
  src/main/java/qastudio/backend/domain/auth/service/AuthCommandServiceImpl.java
  src/main/java/qastudio/backend/global/security/SecurityConfig.java
Labels: :hammer: Refactor

#125 ✨ Feature: 헤더에서 토큰 추출 메소드 추가
  src/main/java/qastudio/backend/global/security/jwt/JwtTokenFilter.java
Labels: :hammer: Refactor

#127 Fix: login fix
  src/main/java/qastudio/backend/domain/auth/controller/AuthController.java
  src/main/java/qastudio/backend/domain/auth/service/AuthCommandService.java
  src/main/java/qastudio/backend/domain/auth/service/AuthCommandServiceImpl.java
  src/main/java/qastudio/backend/global/security/jwt/JwtTokenFilter.java
  src/main/java/qastudio/backend/global/security/oauth/OAuth2SuccessHandler.java
Labels: 🐞 BugFix

#129 🔨 Refactor: 일반 로그인 시 response 수정
  src/main/java/qastudio/backend/domain/auth/controller/AuthController.java
  src/main/java/qastudio/backend/domain/auth/converter/AuthConverter.java
  src/main/java/qastudio/backend/domain/auth/dto/response/AuthResponse.java
  src/main/java/qastudio/backend/domain/auth/service/AuthCommandService.java
  src/main/java/qastudio/backend/domain/auth/service/AuthCommandServiceImpl.java
Labels: :hammer: Refactor

#133 ✨ Feature: 역할-시나리오 생성/수정 api 구현
  src/main/java/qastudio/backend/domain/project/controller/CharacterController.java
  src/main/java/qastudio/backend/domain/project/converter/CharacterConverter.java
  src/main/java/qastudio/backend/domain/project/entity/CharacterTable.java
  src/main/java/qastudio/backend/domain/project/repository/CharacterTableRepository/CharacterTableRepositoryImpl.java
  src/main/java/qastudio/backend/domain/project/repository/Page/PageRepositoryCustom.java
  src/main/java/qastudio/backend/domain/project/repository/Page/PageRepositoryImpl.java
  src/main/java/qastudio/backend/domain/project/repository/PageRole/PageRoleRepositoryImpl.java
  src/main/java/qastudio/backend/domain/project/service/CharacterCommandService.java
  src/main/java/qastudio/backend/domain/project/service/CharacterCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/scenario/entity/ActionTable.java
  src/main/java/qastudio/backend/domain/scenario/entity/Feature.java
  src/main/java/qastudio/backend/domain/scenario/entity/Scenario.java
  src/main/java/qastudio/backend/domain/scenario/repository/FeatureRepository.java
Labels: ✨ Feature

#130 🔨 Refactor: 소셜 로그인/회원가입, 계정 추가 로직 수정
  src/main/java/qastudio/backend/domain/auth/controller/AuthController.java
  src/main/java/qastudio/backend/domain/auth/converter/AuthConverter.java
  src/main/java/qastudio/backend/domain/auth/dto/request/AuthRequest.java
  src/main/java/qastudio/backend/domain/auth/service/AuthCommandService.java
  src/main/java/qastudio/backend/domain/auth/service/AuthCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/auth/service/AuthQueryService.java
  src/main/java/qastudio/backend/domain/auth/service/AuthQueryServiceImpl.java
  src/main/java/qastudio/backend/domain/user/repository/AccountTable/AccountTableRepository.java
  src/main/java/qastudio/backend/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/qastudio/backend/global/security/SecurityConfig.java
  src/main/java/qastudio/backend/global/security/jwt/JwtTokenFilter.java
  src/main/java/qastudio/backend/global/security/jwt/JwtTokenProvider.java
  src/main/java/qastudio/backend/global/security/oauth/CustomOAuth2UserService.java
  src/main/java/qastudio/backend/global/security/oauth/OAuth2SuccessHandler.java
  src/main/java/qastudio/backend/global/security/oauth/OAuth2UserInfo.java
  src/main/java/qastudio/backend/global/security/oauth/handler/OAuth2FailureHandler.java
  src/main/java/qastudio/backend/global/security/oauth/handler/OAuth2SuccessHandler.java
Labels: :hammer: Refactor

#137 🔨 Refactor: 프론트 redirection_url 수정
  src/main/java/qastudio/backend/global/security/oauth/handler/OAuth2FailureHandler.java
  src/main/java/qastudio/backend/global/security/oauth/handler/OAuth2SuccessHandler.java
Labels: :hammer: Refactor

#136 ✨ Feature: 역할/시나리오 생성 시 user 정보 추가 및 경로 수정
  src/main/java/qastudio/backend/domain/project/controller/CharacterController.java
  src/main/java/qastudio/backend/domain/project/converter/CharacterConverter.java
  src/main/java/qastudio/backend/domain/project/entity/CharacterTable.java
  src/main/java/qastudio/backend/domain/project/service/CharacterCommandService.java
  src/main/java/qastudio/backend/domain/project/service/CharacterCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/scenario/entity/Scenario.java
  src/main/java/qastudio/backend/domain/user/entity/User.java
Labels: ✨ Feature, :hammer: Refactor

#139 🔨 Refactor: 소셜 로그인 시 auth 누락 문제 해결 및 redis 세팅
  build.gradle
  src/main/java/qastudio/backend/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/qastudio/backend/global/config/RedisConfig.java
  src/main/java/qastudio/backend/global/security/jwt/JwtTokenFilter.java
  src/main/java/qastudio/backend/global/security/jwt/JwtTokenProvider.java
  src/main/java/qastudio/backend/global/security/oauth/handler/OAuth2SuccessHandler.java
Labels: :hammer: Refactor

#145 ✨ Feature: 팀원의 마이페이지 조회 API
  src/main/java/qastudio/backend/domain/user/controller/UserController.java
  src/main/java/qastudio/backend/domain/user/converter/UserConverter.java
  src/main/java/qastudio/backend/domain/user/dto/response/UserResponse.java
Labels: ✨ Feature

#143 🔨 Refactor: Redis 적용하여 로그인/회원가입 관리
  src/main/java/qastudio/backend/domain/auth/controller/AuthController.java
  src/main/java/qastudio/backend/domain/auth/service/AuthCommandService.java
  src/main/java/qastudio/backend/domain/auth/service/AuthCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/auth/service/AuthQueryService.java
  src/main/java/qastudio/backend/domain/auth/service/AuthQueryServiceImpl.java
  src/main/java/qastudio/backend/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/qastudio/backend/global/config/RedisConfig.java
  src/main/java/qastudio/backend/global/redis/RedisConfig.java
  src/main/java/qastudio/backend/global/security/jwt/JwtTokenFilter.java
  src/main/java/qastudio/backend/global/security/jwt/JwtTokenProvider.java
  src/main/java/qastudio/backend/global/security/oauth/CustomOAuth2UserService.java
  src/main/java/qastudio/backend/global/security/oauth/handler/OAuth2SuccessHandler.java
Labels: ✨ Feature, :hammer: Refactor

#142 🐞 Fix: 시나리오 삭제 시 액션까지 삭제되게 수정
  src/main/java/qastudio/backend/domain/scenario/entity/Scenario.java
Labels: 🐞 BugFix

#150 🔨 Refactor: 사이드바 response 수정 및 예외 처리
  src/main/java/qastudio/backend/domain/auth/service/AuthCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/user/converter/UserConverter.java
  src/main/java/qastudio/backend/domain/user/dto/response/UserResponse.java
  src/main/java/qastudio/backend/domain/user/service/UserQueryServiceImpl.java
  src/main/java/qastudio/backend/global/security/SecurityConfig.java
  src/main/java/qastudio/backend/global/security/jwt/JwtTokenFilter.java
  src/main/java/qastudio/backend/global/security/jwt/JwtTokenProvider.java
Labels: :hammer: Refactor

#151 ✨ Feature: 역할/시나리오 관련 커스텀 예외처리 추가
  src/main/java/qastudio/backend/domain/project/controller/CharacterController.java
  src/main/java/qastudio/backend/domain/project/service/CharacterCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/project/service/CharacterQueryServiceImpl.java
  src/main/java/qastudio/backend/domain/scenario/service/ScenarioCommandServiceImpl.java
  src/main/java/qastudio/backend/domain/scenario/service/ScenarioQueryServiceImpl.java
  src/main/java/qastudio/backend/global/apiPayload/code/exception/custom/AiServerException.java
  src/main/java/qastudio/backend/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ Feature

#157 ✨ Feature - 역할 리스트 조회 시 역할 관련 시나리오, 역할별 접근 가능 경로 응답
  src/main/java/qastudio/backend/domain/project/converter/CharacterConverter.java
  src/main/java/qastudio/backend/domain/project/dto/response/CharacterResponse.java
  src/main/java/qastudio/backend/domain/project/repository/CharacterTableRepository/CharacterTableRepositoryImpl.java
  src/main/java/qastudio/backend/domain/project/service/CharacterQueryService.java
Labels: ✨ Feature, :hammer: Refactor

#160 🐞 Fix: 프로젝트 별 역할 list에 characterDescription 추가
  src/main/java/qastudio/backend/domain/project/converter/CharacterConverter.java
Labels: 🐞 BugFix
